name: Test deploy per environment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true

env:
  RELEASE_NAME: App-Release

jobs:
  deploy:
    name: deploy
    strategy:
      matrix:
        projectName: [coding, codingv2, codingv3]
        kind: ['windows']
        include:
          - kind: windows
            os: windows-latest
            target: win-x64       
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: start deploying
        run: | 
          echo "environment is ${{ inputs.environment }}"
          echo "${{ matrix.projectName }} building"

      - name: build
        shell: bash
        run: | 
          echo "${{ matrix.projectName }}""
          # Build everything
          dotnet publish ${{ matrix.projectName }}/*.csproj --runtime "${{ matrix.target }}" -c Release -o "$matrix.projectName"
          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${matrix.projectName}.zip" "./${matrix.projectName}/*"
          else
          tar czvf "${matrix.projectName}.tar.gz" "$matrix.projectName"
          fi
          # Delete output directory
          rm -r "$matrix.projectName"

      - name: post-build
        run: echo "post build"