name: Test deploy per environment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true
      choice:
        type: choice
        description: Choose element to deploy
        required: true
        options:
        - Functions
        - Web Client
        - Web API
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: ${{ inputs.environment == 'Dev'}}
    steps:
      - uses: actions/checkout@v2
      - name: start deploying
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
  deploy-stage:
    runs-on: ubuntu-latest
    if: ${{ inputs.environment == 'Stage'}}
    steps:
      - uses: actions/checkout@v2
      - name: start deploying
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}