name: Test deploy per environment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true

parameters:
  - name: projectNames
    type: string
    default: coding
    values: 
      - coding
      - codingv2
      - codingv3

jobs:
  - job: Deploy   
    if: ${{ inputs.environment == 'Dev'}}  
    steps:      
      - uses: actions/checkout@v2          
      - name: start deploying
      - ${{ each projectName in parameters.projectNames }}:
        -script : echo ${{ projectName.Key }} ${{projectName.Value }}