name: Test deploy per environment

parameters:
  - name: projectNames
    type: string
    default: coding
    values: 
      - coding
      - codingv2
      - codingv3

jobs:
  - job: deploy   
    steps:      
      - ${{ each projectName in parameters.projectNames }}:
        -script : echo ${{ projectName.Key }} ${{projectName.Value }}