name: Test deploy per environment

parameters:
  - name: projectNames
    type: string
    default: coding
    values: 
      - coding
      - codingv2
      - codingv3

trigger: none

jobs:
  - job: testDeploy
    displayName: testing deploy   
    steps:      
      - ${{ each parameter in parameters }}:
      - script: echo ${{ parameter.Key }} 
      - script: echo ${{ parameter.Value }}

# steps: 
# - ${{ each parameter in parameters }}:
#   - script: echo ${{ parameter.Key }} 
#   - script: echo ${{ parameter.Value }}