name: Test deploy per environment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true

parameters:
  - name: projectNames
    type: string
    default: coding
    values: 
      - coding
      - codingv2
      - codingv3

jobs:
  - job: Deploy
    strategy:
      matrix:
        kind: ['windows']
        include:
          - kind: windows
            os: windows-latest
            target: win-x64       
    runs-on: ${{ matrix.os }}
    if: ${{ inputs.environment == 'Dev'}}  
    steps:      
      - uses: actions/checkout@v2          
      - name: start deploying
      - ${{ each projectName in parameters.projectNames }}:
        -script : echo ${{ projectName }}
        run: | 
          echo "environment is ${{ inputs.environment }}"

      - name: build
        shell: bash
        run:          
          release_name= "${{ projectName }}"
          # Build everything
          dotnet publish ${{ release_name }}/*.csproj --runtime "${{ matrix.target }}" -c Release -o "$release_name"
          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
          tar czvf "${release_name}.tar.gz" "$release_name"
          fi
          # Delete output directory
          rm -r "$release_name"